github:
  client:
    id: 6b94612764d44e4ce138
    secret: 0f6feb2bc76c38b3a188a967dc4022a1d4fc589c
  redirect:
    uri: http://localhost:8887/callback
logging:
  file: ./logs/community.log
  file.max-history: 30
  file.max-size: 50MB
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: life.maijiang.community.model
server:
  port: 8887
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    url: jdbc:mysql:///homework1
    username: root
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  redis:
    # Redis 服务器地址
    host: 127.0.0.1
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码
    password:
    # 连接超时时间（ms)
    timeout: 300
    # Spring Boot 2.0 以后默认使用的客户端
    jedis:
      pool:
        # 连接池最大连接数（<0没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（<0没有限制）
        max-wait: -1ms
        # 连接池中最大空闲链接
        max-idle: 0
        # 连接池中最小空闲链接
        min-idle: 8
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
      shutdown-timeout: 100ms
    # Redis 数据库索引（默认为0）
    database: 0


ucloud:
  ufile:
    bucket-name: maijiang
    expiresDuration: 315360000
    private-key: ccbafecc-f172-4558-b294-63c18f16bb3e
    public-key: TOKEN_b60b73e8-77a0-4749-91fc-d8a10e7d9a5b
    region: cn-gd
    suffix: ufileos.compo
