package life.maijiang.community.mapper;

import java.util.List;
import life.maijiang.community.model.Favour;
import life.maijiang.community.model.FavourExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FavourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    long countByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int deleteByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int insert(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int insertSelective(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    List<Favour> selectByExampleWithRowbounds(FavourExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    List<Favour> selectByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    Favour selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Favour record, @Param("example") FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int updateByExample(@Param("record") Favour record, @Param("example") FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int updateByPrimaryKeySelective(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    int updateByPrimaryKey(Favour record);
}