package life.maijiang.community.mapper;

import java.util.List;
import life.maijiang.community.model.TagField;
import life.maijiang.community.model.TagFieldExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    long countByExample(TagFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int deleteByExample(TagFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int insert(TagField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int insertSelective(TagField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    List<TagField> selectByExampleWithRowbounds(TagFieldExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    List<TagField> selectByExample(TagFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    TagField selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") TagField record, @Param("example") TagFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int updateByExample(@Param("record") TagField record, @Param("example") TagFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int updateByPrimaryKeySelective(TagField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_field
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    int updateByPrimaryKey(TagField record);
}