package life.maijiang.community.model;

public class Favour {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.user_account_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private String userAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.type_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.status
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private String gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favour.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private String gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.id
     *
     * @return the value of favour.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.id
     *
     * @param id the value for favour.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.user_account_id
     *
     * @return the value of favour.user_account_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public String getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.user_account_id
     *
     * @param userAccountId the value for favour.user_account_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId == null ? null : userAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.type_id
     *
     * @return the value of favour.type_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.type_id
     *
     * @param typeId the value for favour.type_id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.type
     *
     * @return the value of favour.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.type
     *
     * @param type the value for favour.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.status
     *
     * @return the value of favour.status
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.status
     *
     * @param status the value for favour.status
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.gmt_create
     *
     * @return the value of favour.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.gmt_create
     *
     * @param gmtCreate the value for favour.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favour.gmt_modified
     *
     * @return the value of favour.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public String getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favour.gmt_modified
     *
     * @param gmtModified the value for favour.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setGmtModified(String gmtModified) {
        this.gmtModified = gmtModified == null ? null : gmtModified.trim();
    }
}