package life.maijiang.community.model;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.name
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.name
     *
     * @return the value of tag.name
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.name
     *
     * @param name the value for tag.name
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.type
     *
     * @return the value of tag.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.type
     *
     * @param type the value for tag.type
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.gmt_create
     *
     * @return the value of tag.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.gmt_create
     *
     * @param gmtCreate the value for tag.gmt_create
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.gmt_modified
     *
     * @return the value of tag.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.gmt_modified
     *
     * @param gmtModified the value for tag.gmt_modified
     *
     * @mbg.generated Mon Oct 28 15:07:23 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}