package life.maijiang.community.model;

public class TagField {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_field.id
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_field.name
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_field.gmt_create
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_field.gmt_modified
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_field.id
     *
     * @return the value of tag_field.id
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_field.id
     *
     * @param id the value for tag_field.id
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_field.name
     *
     * @return the value of tag_field.name
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_field.name
     *
     * @param name the value for tag_field.name
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_field.gmt_create
     *
     * @return the value of tag_field.gmt_create
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_field.gmt_create
     *
     * @param gmtCreate the value for tag_field.gmt_create
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_field.gmt_modified
     *
     * @return the value of tag_field.gmt_modified
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_field.gmt_modified
     *
     * @param gmtModified the value for tag_field.gmt_modified
     *
     * @mbg.generated Thu Nov 21 11:02:11 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}